name: Test with Mocha

on:
  push:
    branches:
      - "master"

  pull_request:
    branches:
      - "master"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Clone Source Code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: yarn install

      - name: Compile
        run: yarn compile

      - name: Test
        run: yarn test
